### ISSUE TITLE
Testing & Integration Questions

### ISSUE THREAD

**Issue by danilashtefan** [andalisolutions/anaf-php#27]
HI, first of all, thank you for such an amazing work of making usage of governmental web service easy and accessible! But before the integration I had couple of questions:

1) It is mentioned that this is charged API. Where I can find price and conditions?
2) Before integrating I wanted to try ANAF API in Postman (https://static.anaf.ro/static/10/Anaf/Informatii_R/doc_WS_V6.txt) but when I try to POST I get either 404, or 200, but with <title>Mentenanta sistem</title>. 

Tho, I am trying without any authorisation, is there a token I need to obtain (could find any clear info).

Many thanks in advance!

**Comment by ciungulete** [comment]
Hello,

Thank you for reaching out with your inquiries. Here are the clarifications you need:

1. Initially, there was consideration for making the package as a paid service, which is why you might have come across references suggesting that. However, I decided against monetizing it, and as a result, the package is now freely available and open source. I have updated the relevant descriptions to reflect this change, removing any confusion regarding charges.

2. It seems you've encountered issues while attempting to access the API via Postman. The version you referred to (V6) has been succeeded by a newer version, [V8](https://static.anaf.ro/static/10/Anaf/Informatii_R/Servicii_web/doc_WS_V8.txt). This api endpoint allows for the retrieval of public data about companies without requiring a token. If you wish to utilize e-factura services, a token will be necessary. 

Should you have any further questions or need additional assistance, please don't hesitate to ask.

Best regards,
